# .air.toml
# Config file for [Air](https://github.com/air-verse/air) in TOML format

root = "."
tmp_dir = "tmp"

[build]
# Build the Go application
cmd = "cd cmd/server && go build -o ../../tmp/main ."
# Binary file produced by `cmd`
bin = "tmp/main"
# Command to run the built binary
full_bin = "./tmp/main"
# Watch these filename extensions for Go rebuilds
include_ext = ["go", "html"]
# Ignore these directories
exclude_dir = ["tmp", "node_modules"]
# It's not necessary to trigger build each time file changes if it's too frequent.
delay = 1000 # ms
# Stop running old binary when build errors occur.
stop_on_error = true
# Send Interrupt on Windows before "air -w" exits
# (doesn't work on windows, the kill command will be used instead)
send_interrupt = false
# Delay after sending Interrupt
kill_delay = 500 # ms

[log]
# Show log time
time = false

[color]
# Customize each part's color
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# Delete tmp directory on exit
clean_on_exit = true
