// Code generated by genmodules.go. DO NOT EDIT.

package app

import (
	"github.com/nfrund/goby/internal/modules/announcer"
	"github.com/nfrund/goby/internal/modules/examples/chat"
	"github.com/nfrund/goby/internal/modules/examples/profile"
	"github.com/nfrund/goby/internal/modules/examples/wargame"
)

func announcerDeps(deps Dependencies) announcer.Dependencies {
	return announcer.Dependencies{
		LiveQueryService: deps.LiveQueryService,
		Publisher:        deps.Publisher,
	}
}
func chatDeps(deps Dependencies) chat.Dependencies {
	return chat.Dependencies{
		Publisher:       deps.Publisher,
		Subscriber:      deps.Subscriber,
		Renderer:        deps.Renderer,
		TopicMgr:        deps.TopicMgr,
		PresenceService: deps.PresenceService,
	}
}
func profileDeps(deps Dependencies) profile.Dependencies {
	return profile.Dependencies{
		FileRepository: deps.FileRepository,
	}
}
func wargameDeps(deps Dependencies) wargame.Dependencies {
	return wargame.Dependencies{
		Publisher:    deps.Publisher,
		Subscriber:   deps.Subscriber,
		Renderer:     deps.Renderer,
		TopicMgr:     deps.TopicMgr,
		ScriptEngine: deps.ScriptEngine,
	}
}
