// Code generated by genmodules.go. DO NOT EDIT.

package app

import (
	"github.com/nfrund/goby/internal/module"
	"github.com/nfrund/goby/internal/modules/announcer"
	"github.com/nfrund/goby/internal/modules/examples/chat"
	"github.com/nfrund/goby/internal/modules/examples/profile"
	"github.com/nfrund/goby/internal/modules/examples/wargame"
)

// NewModules returns all active modules for the application.
// Code generated by genmodules.go. DO NOT EDIT.
func NewModules(deps Dependencies) []module.Module {
	return []module.Module{
		announcer.New(announcerDeps(deps)),
		chat.New(chatDeps(deps)),
		profile.New(profileDeps(deps)),
		wargame.New(wargameDeps(deps)),
	}
}
