// Code generated by genroutes; DO NOT EDIT.
//go:build !dev
// +build !dev

package modules

import (
	// Ensure module routes init() self-register with the registry.
	_ "github.com/nfrund/goby/internal/modules/wargame/http/routes"
)
