// genmodules generates module registration code
package main
	import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"text/template"
)

type ModuleInfo struct {
	Name        string
	PackageName string // Go package name (lowercase)
	ImportPath  string
	Deps        []string // Field names needed from Dependencies
}

type DepField struct {
	Name string
	Type string
}

var depFieldMap = map[string]string{
	"Renderer":         "deps.Renderer",
	"Publisher":        "deps.Publisher",
	"Subscriber":       "deps.Subscriber",
	"TopicMgr":         "deps.TopicMgr",
	"PresenceService":  "deps.PresenceService",
	"ScriptEngine":     "deps.ScriptEngine",
	"LiveQueryService": "deps.LiveQueryService",
	"FileRepository":   "deps.FileRepository",
}

func main() {
	modulesDir := "internal/modules"
	moduleInfos, err := findModules(modulesDir)
	if err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	if len(moduleInfos) == 0 {
		fmt.Println("No modules found")
		return
	}
	sort.Slice(moduleInfos, func(i, j int) bool {
		return moduleInfos[i].Name < moduleInfos[j].Name
	})
	data := struct {
		Modules    []ModuleInfo
		DepFieldMap map[string]string
	}{
		Modules:    moduleInfos,
		DepFieldMap: depFieldMap,
	}
	if err := genFile("internal/app/modules.gen.go", modulesTmpl, data); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated internal/app/modules.gen.go")
	if err := genFile("internal/app/dependencies.gen.go", depsTmpl, data); err != nil {
		fmt.Fprintf(os.Stderr, "Error: %v\n", err)
		os.Exit(1)
	}
	fmt.Println("Generated internal/app/dependencies.gen.go")
}

func findModules(base string) ([]ModuleInfo, error) {
	var modules []ModuleInfo
	
	// Search in base directory (for modules directly under internal/modules)
	mods, err := findModulesInDir(base, "")
	if err != nil {
		return nil, err
	}
	modules = append(modules, mods...)
	
	// Search in examples subdirectory
	examplesDir := filepath.Join(base, "examples")
	if fi, err := os.Stat(examplesDir); err == nil && fi.IsDir() {
		mods, err := findModulesInDir(examplesDir, "examples/")
		if err != nil {
			return nil, err
		}
		modules = append(modules, mods...)
	}
	
	return modules, nil
}

func findModulesInDir(base, prefix string) ([]ModuleInfo, error) {
	var modules []ModuleInfo
	entries, err := os.ReadDir(base)
	if err != nil {
		return nil, err
	}
	for _, e := range entries {
		if !e.IsDir() || strings.HasPrefix(e.Name(), ".") {
			continue
		}
		name := e.Name()
		path := filepath.Join(base, name, "module.go")
		if _, err := os.Stat(path); err != nil {
			continue
		}
		info, err := parseModule(path, name, prefix)
		if err != nil {
			fmt.Fprintf(os.Stderr, "Warning: %s%s: %v\n", prefix, name, err)
			continue
		}
		modules = append(modules, info)
	}
	return modules, nil
}

func parseModule(path, name, prefix string) (ModuleInfo, error) {
	fset := token.NewFileSet()
	node, err := parser.ParseFile(fset, path, nil, 0)
	if err != nil {
		return ModuleInfo{}, err
	}
	
	var deps []string
	ast.Inspect(node, func(n ast.Node) bool {
		// Look for type Dependencies struct { ... }
		gen, ok := n.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			return true
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != "Dependencies" {
				continue
			}
			st, ok := ts.Type.(*ast.StructType)
			if !ok {
				continue
			}
			for _, field := range st.Fields.List {
				for _, fieldName := range field.Names {
					deps = append(deps, fieldName.Name)
				}
			}
		}
		return false
	})
	
	importPath := "github.com/nfrund/goby/internal/" + strings.TrimPrefix(path, "internal/")
	importPath = strings.TrimSuffix(importPath, "/module.go")
	return ModuleInfo{
		Name:        name,
		PackageName: name, // Go package names are lowercase
		ImportPath:  importPath,
		Deps:        deps,
	}, nil
}

func genFile(path, tmpl string, data interface{}) error {
	t, err := template.New("").Parse(tmpl)
	if err != nil {
		return err
	}
	var buf strings.Builder
	buf.WriteString("// Code generated by genmodules.go. DO NOT EDIT.\n\n")
	if err := t.Execute(&buf, data); err != nil {
		return err
	}
	formatted, err := format.Source([]byte(buf.String()))
	if err != nil {
		formatted = []byte(buf.String())
	}
	return os.WriteFile(path, formatted, 0644)
}

const modulesTmpl = `package app

import (
{{- range .Modules}}
	"{{.ImportPath}}"
{{- end}}
	"github.com/nfrund/goby/internal/module"
)

// NewModules returns all active modules for the application.
// Code generated by genmodules.go. DO NOT EDIT.
func NewModules(deps Dependencies) []module.Module {
	return []module.Module{
{{- range .Modules}}
		{{.PackageName}}.New({{.PackageName}}Deps(deps)),
{{- end}}
	}
}
`

const depsTmpl = `package app

import (
{{- range .Modules}}
	"{{.ImportPath}}"
{{- end}}
)

{{- range .Modules}}
func {{.PackageName}}Deps(deps Dependencies) {{.PackageName}}.Dependencies {
	return {{.PackageName}}.Dependencies{
{{- range .Deps}}
		{{.}}: {{index $.DepFieldMap .}},
{{- end}}
	}
}
{{- end}}
`
